3_Ano/SIO/P1/app_sec/website/auth.py
import re
from flask import Blueprint, render_template, request, flash, redirect, send_file, url_for
from .models import ContactForm, Doctor, Post, User, db, Appointment
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from fpdf import FPDF
import platform
auth = Blueprint('auth', __name__)
FORBIDDEN_CHARS_DICT = {'/': '\'', '\\': '\'', ':': '\:', '*': '\*',
                        '?': '\?', '"': '\"', '<': '\<', '>': '\>', '|': '\|', '-': '\-'}


def replace_all(text):
    for i, j in FORBIDDEN_CHARS_DICT.items():
        text = text.replace(i, j)
    return text


def create_certification(appt):
    if not appt:
        return False
    open("certification.txt", "w").close()
    with open('certification.txt', 'a') as f:
        f.write(f"eHealth Corp\n")
        f.write(f"Appointment results\n\n")
        f.write(f"Appointment ID: {appt.id}\n")
        f.write(f"Doctor: {appt.doctor}\n")
        f.write(f"Patient: {appt.patient}\n")
        f.write(f"Date: {appt.date}\n")
        f.write(f"Time: {appt.time}\n")
        f.write(f"Result: Treated\n")
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("times", size=15)
    f = open("certification.txt", "r")

    for x in f:
        pdf.cell(200, 10, txt=x, ln=1, align='C')

    pdf.output("certification.pdf")
    return True


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('uname')
        password = request.form.get('psw')

        username = replace_all(username)

        user = User.query.filter_by(username=username).first()

        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('auth.user_area', uname=user.username))
            else:
                flash('Incorrect username or password.', category='error')
        else:
            flash('Incorrect username or password.', category='error')
    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get('uname')
        email = request.form.get('email')
        fullname = request.form.get('fullname')
        password1 = request.form.get('psw')
        password2 = request.form.get('confirmpsw')
        username = replace_all(username)

        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username already exists.', category='error')
        elif len(email) < 5:
            flash("Email must be greater than 4 characters.", category='error')
        elif password1 != password2:
            flash("Passwords don't match.", category='error')
        elif len(password1) < 7:
            flash("Password must be at least 7 characters.", category='error')
        elif re.search('[A-Z]', password1) is None:
            flash('Password must contain at least one uppercase letter.', category='error')
        elif re.search('\d', password1) is None:
            flash('Password must contain at least a number.', category='error')
        else:
            new_user = User(email=email, fullname=fullname, password=generate_password_hash(
                password1, method='sha256'), username=username)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created!", category='success')
            return redirect(url_for('views.index'))
    return render_template("signup.html", user=current_user)


@auth.route('/user_area/<string:uname>')
@login_required
def user_area(uname):
    if uname != current_user.username:
        flash("Restricted access.", category="error")
        return redirect(url_for('auth.login'))
    appointments = Appointment.query.filter_by(patient=current_user.username).all()
    contact_requests = ContactForm.query.all() if current_user.username == 'admin' else []
    return render_template("user_area.html", user=current_user, doctors=Doctor.query.all(), contact_requests=contact_requests, appointments=appointments)


@auth.route('/user_area/<string:uname>/download_results/', methods=['GET', 'POST'])
@login_required
def download_results(uname):
    if request.method == "GET":
        if uname != current_user.username:
            flash("Restricted access.", category="error")
            return redirect(url_for('auth.login'))
        contact_requests = ContactForm.query.all() if current_user.username == 'admin' else []
        appointments = Appointment.query.filter_by(patient=current_user.username).all()
        appointment_id = request.args['id']
        if appointment_id:
            appointments = Appointment.query.filter_by(patient=current_user.username).all()
            if platform.system() == 'Windows':
                path = '..\\..\\certification.pdf'
            else:
                path = '../../certification.pdf'
            appt = Appointment.query.filter_by(id=appointment_id).first()

            if not appt:
                flash("Appointment not found", category="error")
            elif not create_certification(appt):
                flash("Appointment not found", category="error")
            else:
                if appt.patient == current_user.username:
                    return send_file(path, as_attachment=True)
                else:
                    flash("Appointment not found", category="error")

            return render_template("user_area.html", user=current_user, doctors=Doctor.query.all(), contact_requests=contact_requests, appointments=appointments)
        else:
            flash("Appointment not found", category="error")
            return render_template("user_area.html", user=current_user, doctors=Doctor.query.all(), contact_requests=contact_requests, appointments=appointments)


@auth.route('/user_area/<string:uname>/new_appointment/', methods=['POST', 'GET'])
@login_required
def schedule_appointment(uname):
    if uname != current_user.username:
        flash("Restricted access.", category="error")
        return redirect(url_for('auth.login'))
    doctor_name = request.form['doctor']
    date = request.form['date']
    time = request.form['time']
    contact_requests = ContactForm.query.all() if current_user.username == 'admin' else []
    new_appointment = Appointment(doctor=doctor_name, patient=current_user.username, date=date, time=time)
    db.session.add(new_appointment)
    db.session.commit()
    appointments = Appointment.query.filter_by(patient=current_user.username).all()
    flash("Appointment scheduled!", category="success")
    return render_template("user_area.html", user=current_user, doctors=Doctor.query.all(), appointments=appointments, contact_requests=contact_requests)


@auth.route('/forum/<string:uname>', methods=['POST', 'GET'])
@login_required
def forum(uname):
    if uname != current_user.username:
        flash("Restricted access.", category="error")
        return redirect(url_for('auth.login'))
    return render_template("forum.html", user=current_user, posts=Post.query.all())


@auth.route('/forum/<string:uname>/newpost/', methods=['POST', 'GET'])
@login_required
def newpost(uname):
    if uname != current_user.username:
        flash("Restricted access.", category="error")
        return redirect(url_for('auth.login'))
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        new_post = Post(title=title, content=content, user_username=current_user.username)
        db.session.add(new_post)
        db.session.commit()
        return render_template("forum.html", user=current_user, posts=Post.query.all())
    return render_template("newpost.html", user=current_user)

3_Ano/SIO/P1/app_sec/website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="icon" href="https://cdn-icons-png.flaticon.com/512/121/121731.png" type="image/icon type">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	{% block head %}{% endblock %}
</head>

<body>
	<script src="http://code.jquery.com/jquery.min.js"></script>
	<script src="static/js/bootstrap.min.js"></script>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="{{url_for('views.index')}}">eHealth Corp</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
			aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('views.index')}}">Home <span class="sr-only">(current)</span></a>
				</li>
				{% if user.is_authenticated %}
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('auth.forum', uname=user.username)}}">Forum</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('auth.user_area', uname=user.username)}}">User area</a>
				</li>
				{% endif %}
			</ul>
			<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
				{% if user.is_authenticated %}
				<div class="btn-group mr-2" role="group" aria-label="First group">
					<a class="btn btn-outline-success my-2 my-sm-0" href="{{url_for('auth.logout')}}">Log Out</a>
				</div>
				{% else %}
				<div class="btn-group mr-2" role="group" aria-label="First group">
					<a class="btn btn-outline-success my-2 my-sm-0" href="{{url_for('auth.login')}}">Log In</a>
				</div>
				<div class="btn-group mr-2" role="group" aria-label="Second group">
					<a class="btn btn-outline-success my-2 my-sm-0" href="{{url_for('auth.signup')}}">Sign Up</a>
				</div>
				{% endif %}

			</div>
		</div>
	</nav>
	{% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alert-dismissable fade show" role="alert">
                        {{ message | safe}}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissable fade show" role="alert">
                        {{ message | safe}}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
	<br>
	<br>
	{% block body %}{% endblock %}
	<!-- Footer -->
	<footer class="page-footer font-small blue">

		<!-- Copyright -->
		<div class="footer-copyright text-center py-3">© All rights reserved
			<a href="/"> eHealth Corp</a>
		</div>
		<!-- Copyright -->

	</footer>
	<!-- Footer -->
</body>

</html>

3_Ano/SIO/P1/app_sec/website/templates/forum.html
{% extends 'base.html' %}

{% block head %}
<title>Forum</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="pagination-centered">
        <h1 class="pagination-centered"><strong>Forum</strong></h1>
        <h1 class="pagination-centered">Welcome, {{ user.username }}</h1>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Publish a new post
        </button>

        <br>
        <br>
        {% if posts | length != 0 %}
        {% for post in posts %}
        <h2 class="pagination-centered">{{post.title}}</h2>
        <p class="pagination-centered">{{post.content}}</p>
        <p class="pagination-centered">Published by {{post.user_username}} at {{post.date}} {{post.time}}</p>
        <br>
        {% endfor %}
    </div>
</div>

{% endif %}
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h1>New Post</h1>
                <form action="/forum/{{user.username}}/newpost/" method="post">
                    <div class="mb-5 row">
                        <div class="col">
                            <label>Title</label>
                            <input type="text" class="form-control" id="title" name="title" required maxlength="50">
                        </div>
                    </div>
                    <div class="mb-5">
                        <label for="content">Content</label>
                        <textarea required class="form-control" id="content" name="content" rows="5"></textarea>
                    </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="submit" value="Submit">Submit</button>

                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}

3_Ano/SIO/P1/app_sec/website/templates/index.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<div class="container h-100">
	<div class="row h-100 justify-content-center align-items-center">
		<h1><strong>Welcome to eHealth Corp</strong></h1>
	</div>
</div>
<div class="container h-100">
	<div class="row h-100 justify-content-center align-items-center">
		<p>Here's what we offer: </p>
	</div>
</div>
<div class="container h-100">
	<div class="row h-100 justify-content-center align-items-center">
		<ul>
			<li>You can schedule appointments online and choose your doctor</li>
			<li>You can post in our forum</li>
			<li>You can search for a doctor in our database</li>
		</ul>
	</div>
</div>
<div class="container h-100">
	<div class="row h-100 justify-content-center align-items-center">
		<h4>Search for a doctor: </h4>
	</div>
</div>


<div class="container h-100">
	<div class="row h-100 justify-content-center align-items-center">
		<form action="/search" method="GET">
			<input value="{{query}}" class="input-large" type="text" name="query">
			<button class="btn btn-primary" type="submit" value="Search">Search</button>
		</form>
		{% if doctors | length != 0 %}
		<table class="table table-bordered">
			<caption></caption>
			<th>Name</th>
			<th>Email</th>
			<th>Phone Number</th>
			{% for doc in doctors %}
			<tr>
				<td>{{ doc.name }}</td>
				<td>{{ doc.email }}</td>
				<td>{{ doc.phone }}</td>
			</tr>
			{% endfor %}
		</table>
		{% else %}
		<div class="container h-100">
			<div class="row h-100 justify-content-center align-items-center">
				No search results.
				{% endif %}
			</div>
		</div>

		<!-- Button trigger modal -->
		<div class="container h-100">
			<div class="row h-100 justify-content-center align-items-center">
				<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
					Contact us!
				</button>
			</div>
		</div>

		<!-- Modal -->
		<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<h1>Contact us!</h1>
						<form id="contact_form" action="contact-company" name="contact_form" method="post">
							<div class="mb-5 row">
								<div class="col">
									<label>First Name</label>
									<input type="text" class="form-control" id="first_name" name="first_name" required maxlength="50">
								</div>
								<div class="col">
									<label>Last Name</label>
									<input type="text" required maxlength="50" class="form-control" id="last_name" name="last_name">
								</div>
							</div>
							<div class="mb-5 row">
								<div class="col">
									<label for="email_addr">Email address</label>
									<input type="email_addr" required maxlength="50" class="form-control" id="email_addr" name="email_addr"
										placeholder="name@example.com">
								</div>
								<div class="col">
									<label for="phone_input">Phone</label>
									<input type="number" min=0 required maxlength="50" class="form-control" id="phone_input" name="phone_input"
										placeholder="Phone">
								</div>
							</div>
							<div class="mb-5">
								<label for="message">Message</label>
								<textarea required class="form-control" id="message" name="message" rows="5"></textarea>
							</div>
					</div>
					<div class="modal-footer">
						<button class="btn btn-primary" type="submit" value="Submit">Submit</button>

						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					</div>
					</form>

				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

3_Ano/SIO/P1/app_sec/website/templates/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col text-center">
            <div class="container">
                <div class="pagination-centered">
                    <h1>Login</h1>
                </div>
            </div>
            <div class="container">
                <div class="pagination-centered">
                    <form action="login" method="post">
                        <div class="form-group">
                            <label for="uname"><strong>Username</strong></label>
                            <input type="text" name="uname" class="form-control" id="uname" aria-describedby="text" placeholder="Username" required>
                        </div>
                        <div class="form-group">
                            <label for="psw"><strong>Password</strong></label>
                            <input type="password" name="psw" class="form-control" id="psw" placeholder="Password"  required>
                        </div>
                        <button type="submit" class="btn btn-primary">Log In</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

3_Ano/SIO/P1/app_sec/website/templates/newpost.html
{% extends 'base.html' %}

{% block head %}
<title>Publish a Post</title>
{% endblock %}

{% block body %}
<div class="container">
	<div class="pagination-centered">
        <h1 class="pagination-centered">Publish a post in the forum</h1>
        <div class="container">

            <div class="pagination-centered">
                <form method="post">
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label"><strong>Title</strong></label>
                        <input name="title" type="text" class="form-control" id="recipient-name">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label"><strong>Description</strong></label>
                        <textarea name="content" class="form-control" id="message-text"></textarea>
                    </div>
                    <input class="btn" type="submit" value="Post">
                    <a class="btn" href="{{url_for('forum', uname=uname)}}">Cancel</a>
                </form>
            </div>
        </div>
        <br>
</div>
</div>
{% endblock %}

3_Ano/SIO/P1/app_sec/website/templates/signup.html
{% extends 'base.html' %}

{% block head %}
<title>Sign Up</title>
{% endblock %}

{% block body %}

<h1 style="text-align:center">Sign Up</h1>

<div class="container">
    <div class="row">
        <div class="col text-center">
            <div class="container">
                <div class="pagination-centered">
                    <form action="signup" method="post">
                        <div class="form-group">
                            <label for="uname"><strong>Username</strong></label>
                            <input type="text" name="uname" class="form-control" id="uname" aria-describedby="text" placeholder="Username" required>
                        </div>
                        <div class="form-group">
                            <label for="fullname"><strong>Full Name</strong></label>
                            <input type="text" name="fullname" class="form-control" id="fullname" aria-describedby="text" placeholder="Full Name" required>
                        </div>
                        <div class="form-group">
                            <label for="email"><strong>Email</strong></label>
                            <input type="email" name="email" class="form-control" id="email" aria-describedby="text" placeholder="Email" required>
                        </div>
                        <div class="form-group">
                            <label for="psw"><strong>Password</strong></label>
                            <input type="password" name="psw" class="form-control" id="psw" placeholder="Password" required>
                        </div>
                        <div class="form-group">
                            <label for="psw"><strong>Confirm Password</strong></label>
                            <input type="password" name="confirmpsw" class="form-control" id="psw" placeholder="Password" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

3_Ano/SIO/P1/app_sec/website/templates/user_area.html
{% extends 'base.html' %}

{% block head %}
<title>User Area</title>
{% endblock %}

{% block body %}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <h1>{{user.username}}'s personal space </h1>
    </div>
</div>

<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <h1>My info</h1>
        <table class="table table-bordered">
            <caption>
                <th>Username</th>
                <th>Password</th>
                <th>Full Name</th>
                <th>Email</th>
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.fullname }}</td>
                <td>{{ user.email }}</td>
            </tr>
            </caption>
        </table>
    </div>
</div>


<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <h1>My appointments</h1>
        {% if appointments | length != 0 %}
        <table class="table table-bordered">
            <caption>
                <th>Appointment ID</th>
                <th>Doctor Name</th>
                <th>Appointment Date and Time</th>
                {% for a in appointments %}
            <tr>
                <td>{{ a.id }}</td>
                <td>{{ a.doctor }}</td>
                <td>{{ a.date }} {{ a.time }}</td>
            </tr>
            {% endfor %}
            </caption>
        </table>
        {% else %}
        <div class="container h-100">
            <div class="row h-100 justify-content-center align-items-center">
                <p>You have no appointments</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container h-100">
    <form action="/user_area/{{user.username}}/download_results/" method="GET" class="form-inline">
        <div class="form-group mx-sm-3 mb-2">
            <label for="id" class="sr-only">code(ID)</label>
            <input min="1" type="number" step="1" placeholder="Appointment ID" name="id" required>
        </div>
        <button type="submit" class="btn btn-primary mb-2" download="docs/certification.txt">Get Appointment Results</button>
    </form>
</div>
<!-- Only admin can see this. it shows the contact requests executed in the index page -->
{% if user.username == 'admin' %}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        {% if contact_requests | length != 0 %}
        <h1>Contact Requests</h1>
        <table class="table table-bordered">
            <caption></caption>
            <th>Request ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Message</th>
            {% for r in contact_requests %}
            <tr>
                <td>{{ r.id }}</td>
                <td>{{ r.fname }} {{ r.lname }}</td>
                <td>{{ r.email }}</td>
                <td>{{ r.phone }}</td>
                <td>{{ r.message }}</td>
            </tr>
        {% endfor %}
        </table>
        {% else %}
        <p>There are no contact requests</p>
    </div>
</div>
{% endif %}
{% endif %}


<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Schedule an appointment
        </button>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h1>Schedule Appointment</h1>
                <form method="post" action="/user_area/{{user.username}}/new_appointment/">
                    <div class="mb-5 row">
                        <div class="col">
                            <label for="doctor">Choose a doctor:</label>
                            <select id="doctor" name="doctor">
                                {% for d in doctors %}
                                <option value="{{ d.name }}">{{ d.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col">
                            <label for="date">Start date:</label><br>
                            <input type="date" id="date" name="date" value="2022-01-01" min="2022-01-01" max="2024-12-31">
                        </div>
                        <div class="col">
                            <label for="time">Appointment Time</label>
                            <input type="time" id="time" name="time" min="09:00" max="18:00" required>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary" type="submit" value="Submit">Submit</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}